version: "3"

services:
  nodeserver:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s /usr/src/app/docker-entrypoint.sh
    ports:
      - "5000:5000"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - node-network

  db:
    build:
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
